spring:
  application:
    name: auth-service
  config:
    import: "${CONFIG_SERVER_IMPORT:configserver:${CONFIG_SERVER_URL:http://localhost:8888}}"
  cloud:
    config:
      username: ${CONFIG_SERVER_USERNAME:configuser}
      password: ${CONFIG_SERVER_PASSWORD}

eureka:
  client:
    enabled: false
