@file:OptIn(androidx.compose.material3.ExperimentalMaterial3Api::class)

package mx.fixi.app.ui

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.hilt.navigation.compose.hiltViewModel
import mx.fixi.app.data.*

@Composable fun CustomersScreen(vm: OperationsViewModel = hiltViewModel()) { var add by remember { mutableStateOf(false) }; LaunchedEffect(Unit) { vm.loadCustomers() }; Scaffold(topBar = { TopAppBar(title = { Text("Clientes") }, actions = { TextButton({ add = !add }) { Text(if (add) "Cerrar" else "Nuevo") } }) }) { p -> Column(Modifier.padding(p).padding(16.dp)) { if (add) CustomerForm { a, b, c, d -> vm.createCustomer(a, b, c, d); add = false }; if (vm.loading) LinearProgressIndicator(Modifier.fillMaxWidth()); vm.customers.forEach { CustomerRow(it) }; if (vm.customers.isEmpty() && !vm.loading) Text("Sin clientes", Modifier.padding(vertical = 24.dp)); vm.error?.let { Text(it, color = MaterialTheme.colorScheme.error) }; OutlinedButton({ vm.loadCustomers() }, Modifier.fillMaxWidth()) { Text("Actualizar") } } } }
@Composable private fun CustomerRow(x: Customer) = ListItem(headlineContent = { Text(listOfNotNull(x.firstName, x.lastName).joinToString(" ").ifBlank { "Cliente" }) }, supportingContent = { Text(x.email ?: x.phone ?: "Sin contacto") })
@Composable private fun CustomerForm(onSave: (String, String, String, String) -> Unit) { var first by remember { mutableStateOf("") }; var last by remember { mutableStateOf("") }; var email by remember { mutableStateOf("") }; var phone by remember { mutableStateOf("") }; Column { OutlinedTextField(first, { first = it }, Modifier.fillMaxWidth(), label = { Text("Nombre") }); OutlinedTextField(last, { last = it }, Modifier.fillMaxWidth(), label = { Text("Apellidos") }); OutlinedTextField(email, { email = it }, Modifier.fillMaxWidth(), label = { Text("Correo") }); OutlinedTextField(phone, { phone = it }, Modifier.fillMaxWidth(), label = { Text("Teléfono") }); Button({ onSave(first, last, email, phone) }, Modifier.fillMaxWidth(), enabled = first.isNotBlank() && last.isNotBlank()) { Text("Guardar cliente") } } }
@Composable fun InventoryScreen(vm: OperationsViewModel = hiltViewModel()) { LaunchedEffect(Unit) { vm.loadInventory() }; DataScreen("Inventario", vm.loading, vm.error, vm.inventory.isEmpty(), { vm.loadInventory() }) { vm.inventory.forEach { ListItem(headlineContent = { Text(it.name ?: it.sku ?: "Refacción") }, supportingContent = { Text("Existencia: ${it.quantity ?: 0}") }) } } }
@Composable fun OrderDetailScreen(id: String, vm: OperationsViewModel = hiltViewModel()) { var diagnosis by remember { mutableStateOf("") }; var workLog by remember { mutableStateOf("") }; var solution by remember { mutableStateOf("") }; var testName by remember { mutableStateOf("") }; var testPassed by remember { mutableStateOf(false) }; LaunchedEffect(id) { vm.loadOrder(id) }; Scaffold(topBar = { TopAppBar(title = { Text("Detalle de orden") }) }) { p -> LazyColumn(Modifier.padding(p).padding(16.dp)) { item { vm.selectedOrder?.let { order -> Text(order.orderNumber ?: order.id ?: "Orden", style = MaterialTheme.typography.headlineSmall); Text(order.status ?: "Sin estado"); Text(order.customerName ?: "Cliente pendiente"); Row { Button({ vm.orderAction(id, "authorize") }) { Text("Autorizar") }; Spacer(Modifier.width(8.dp)); OutlinedButton({ vm.orderAction(id, "deliver") }) { Text("Entregar") } }; OutlinedTextField(diagnosis, { diagnosis = it }, Modifier.fillMaxWidth(), label = { Text("Diagnóstico") }); OutlinedTextField(workLog, { workLog = it }, Modifier.fillMaxWidth(), label = { Text("Trabajo realizado") }); Button({ vm.updateOrder(id, "IN_REPAIR", diagnosis, workLog) }) { Text("Guardar diagnóstico") }; OutlinedTextField(solution, { solution = it }, Modifier.fillMaxWidth(), label = { Text("Solución") }); Button({ vm.quote(id, solution, 60, 0.0, 0.0, 0.0) }, enabled = solution.isNotBlank()) { Text("Guardar cotización") } }; Text("Timeline", style = MaterialTheme.typography.titleLarge) }; items(vm.timeline) { event -> ListItem(headlineContent = { Text(event.type ?: "Evento") }, supportingContent = { Text(event.description ?: "") }) }; item { Text("Pruebas de reparación", style = MaterialTheme.typography.titleLarge); OutlinedTextField(testName, { testName = it }, Modifier.fillMaxWidth(), label = { Text("Nombre de prueba") }); Row { Checkbox(checked = testPassed, onCheckedChange = { checked -> testPassed = checked }); Text("Aprobada") }; Button({ vm.addTest(id, testName, testPassed, ""); testName = "" }, enabled = testName.isNotBlank()) { Text("Registrar prueba") } }; items(vm.tests) { test -> ListItem(headlineContent = { Text(test.name ?: "Prueba") }, supportingContent = { Text(if (test.passed == true) "Aprobada" else "Pendiente") }) }; item { Text("Evidencias", style = MaterialTheme.typography.titleLarge); EvidencePicker(onSelected = { uri -> vm.addEvidence(id, "evidence-${System.currentTimeMillis()}", "image/*", uri.toString()) }) }; items(vm.evidence) { evidence -> ListItem(headlineContent = { Text(evidence.fileName ?: "Documento") }, supportingContent = { Text(evidence.contentType ?: "") }) }; vm.message?.let { message -> item { Text(message, color = MaterialTheme.colorScheme.primary) } }; vm.error?.let { errorMessage -> item { Text(errorMessage, color = MaterialTheme.colorScheme.error) } } } } }
@Composable private fun DataScreen(title: String, loading: Boolean, error: String?, empty: Boolean, retry: () -> Unit, content: @Composable ColumnScope.() -> Unit) { Scaffold(topBar = { TopAppBar(title = { Text(title) }) }) { p -> Column(Modifier.padding(p).padding(16.dp)) { if (loading) LinearProgressIndicator(Modifier.fillMaxWidth()); if (empty && !loading) Text("Sin información", Modifier.padding(vertical = 24.dp)); content(); error?.let { Text(it, color = MaterialTheme.colorScheme.error, Modifier.padding(vertical = 12.dp)) }; OutlinedButton(onClick = retry, modifier = Modifier.fillMaxWidth()) { Text("Actualizar") } } } }
