import { useEffect,useState,type FormEvent } from 'react'
import { useParams } from 'react-router-dom'
import { BaseLayout } from '@/components/layouts/base-layout'
import { Button } from '@/components/ui/button'
import { Card,CardContent,CardHeader,CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Badge } from '@/components/ui/badge'
import * as api from './api'

const field='w-full rounded-md border bg-background px-3 py-2 text-sm'
const states=['INTAKE','REVIEW','DIAGNOSIS','QUOTED','QUOTE_REJECTED','AUTHORIZED','IN_PROGRESS','QA','COMPLETED','CANCELLED']
export function ServiceOrderDetail(){
 const {id=''}=useParams();const [order,setOrder]=useState<api.ServiceOrder>();const [tests,setTests]=useState<Awaited<ReturnType<typeof api.listRepairTests>>>([]);const [timeline,setTimeline]=useState<Awaited<ReturnType<typeof api.serviceOrderTimeline>>>([]);const [products,setProducts]=useState<api.Product[]>([]);const [evidence,setEvidence]=useState<api.DocumentEvidence[]>([]);const [times,setTimes]=useState<api.TimeEntry[]>([]);const [warranties,setWarranties]=useState<api.WarrantyClaim[]>([]);const [error,setError]=useState('')
 const [work,setWork]=useState({status:'INTAKE',diagnosis:'',workLog:'',assignedUserId:''});const [quote,setQuote]=useState({proposedSolution:'',estimatedMinutes:60,laborAmount:0,partsAmount:0,taxAmount:0});const [test,setTest]=useState({testName:'',passed:true,notes:'',technicianId:''});const [part,setPart]=useState({productId:'',quantity:1});const [time,setTime]=useState({minutes:30,note:''});const [document,setDocument]=useState({fileName:'',contentType:'image/jpeg',storageKey:'',accessLevel:'INTERNAL'});const [warranty,setWarranty]=useState({expiresAt:'',description:''});const [portalLink,setPortalLink]=useState('')
 async function load(){try{const o=await api.getServiceOrder(id);const [t,h,p,d,te,w]=await Promise.all([api.listRepairTests(id),api.serviceOrderTimeline(id),api.listProducts(),api.listEvidence(id),api.listTimeEntries(id),api.listWarrantyClaims(o.customerId)]);setOrder(o);setTests(t);setTimeline(h);setProducts(p);setEvidence(d);setTimes(te);setWarranties(w);setWork({status:o.status,diagnosis:o.diagnosis??'',workLog:o.workLog??'',assignedUserId:o.assignedUserId??''})}catch(e){setError(e instanceof Error?e.message:String(e))}}
 useEffect(()=>{load()},[id])
 async function save(e:FormEvent){e.preventDefault();await api.updateServiceOrder(id,{...work,assignedUserId:work.assignedUserId||null});await load()}
 async function saveQuote(e:FormEvent){e.preventDefault();await api.quoteServiceOrder(id,quote);await load()}
 async function saveTest(e:FormEvent){e.preventDefault();await api.addRepairTest(id,{...test,technicianId:test.technicianId||null});setTest({...test,testName:'',notes:''});await load()}
 async function reserve(e:FormEvent){e.preventDefault();if(!order?.branchId)throw new Error('La orden requiere sucursal');await api.reserveStock({branchId:order.branchId,productId:part.productId,serviceOrderId:id,quantity:part.quantity});setPart({...part,productId:''});await load()}
 async function addTime(e:FormEvent){e.preventDefault();const userId=work.assignedUserId;if(!userId)throw new Error('Asigna un técnico antes de registrar tiempo');await api.addTimeEntry(id,{userId,minutes:time.minutes,note:time.note});setTime({...time,note:''});await load()}
 async function addDocument(e:FormEvent){e.preventDefault();if(!order) return;await api.addEvidence({...document,serviceOrderId:id,customerId:order.customerId});setDocument({...document,fileName:'',storageKey:''});await load()}
 return <BaseLayout title="Orden de servicio" description={id}><div className="grid gap-5 px-4 lg:grid-cols-2 lg:px-6">
  <Card><CardHeader><CardTitle className="flex justify-between">Operación <Badge>{order?.status}</Badge></CardTitle></CardHeader><CardContent><form className="space-y-3" onSubmit={save}><Label>Estado</Label><select className={field} value={work.status} onChange={e=>setWork({...work,status:e.target.value})}>{states.map(s=><option key={s}>{s}</option>)}</select><Label>Diagnóstico</Label><textarea className={field} value={work.diagnosis} onChange={e=>setWork({...work,diagnosis:e.target.value})}/><Label>Bitácora de reparación</Label><textarea className={field} value={work.workLog} onChange={e=>setWork({...work,workLog:e.target.value})}/><Label>Técnico UUID</Label><Input value={work.assignedUserId} onChange={e=>setWork({...work,assignedUserId:e.target.value})}/><Button>Guardar avance</Button></form></CardContent></Card>
  <Card><CardHeader><CardTitle>Cotización y autorización</CardTitle></CardHeader><CardContent><form className="space-y-3" onSubmit={saveQuote}><textarea className={field} required placeholder="Solución propuesta" value={quote.proposedSolution} onChange={e=>setQuote({...quote,proposedSolution:e.target.value})}/><Input type="number" min="1" value={quote.estimatedMinutes} onChange={e=>setQuote({...quote,estimatedMinutes:Number(e.target.value)})}/><div className="grid grid-cols-3 gap-2"><Input type="number" min="0" placeholder="Mano de obra" value={quote.laborAmount} onChange={e=>setQuote({...quote,laborAmount:Number(e.target.value)})}/><Input type="number" min="0" placeholder="Refacciones" value={quote.partsAmount} onChange={e=>setQuote({...quote,partsAmount:Number(e.target.value)})}/><Input type="number" min="0" placeholder="Impuestos" value={quote.taxAmount} onChange={e=>setQuote({...quote,taxAmount:Number(e.target.value)})}/></div><div className="flex flex-wrap gap-2"><Button>Generar cotización</Button>{order?.status==='QUOTED'&&<><Button type="button" variant="outline" onClick={async()=>{await api.authorizeServiceOrder(id,'Autorización registrada en Fixi');await load()}}>Autorizar</Button><Button type="button" variant="destructive" onClick={async()=>{await api.rejectServiceOrder(id,'Cotización rechazada por el cliente');await load()}}>Rechazar</Button><Button type="button" variant="outline" onClick={async()=>{const r=await api.issuePortalToken(id);setPortalLink(`${location.origin}/portal/${r.token}`)}}>Crear enlace para cliente</Button></>}</div>{portalLink&&<Input readOnly value={portalLink} onFocus={e=>e.currentTarget.select()}/>} {order?.quoteTotal!==undefined&&<p>Total: ${order.quoteTotal}</p>}</form></CardContent></Card>
  <Card><CardHeader><CardTitle>Pruebas posteriores</CardTitle></CardHeader><CardContent className="space-y-3"><form className="space-y-2" onSubmit={saveTest}><Input required placeholder="Prueba realizada" value={test.testName} onChange={e=>setTest({...test,testName:e.target.value})}/><textarea className={field} placeholder="Notas" value={test.notes} onChange={e=>setTest({...test,notes:e.target.value})}/><label className="flex gap-2"><input type="checkbox" checked={test.passed} onChange={e=>setTest({...test,passed:e.target.checked})}/>Resultado aprobado</label><Button>Registrar prueba</Button></form>{tests.map(t=><div className="flex justify-between rounded border p-2" key={t.id}><span>{t.testName}</span><Badge variant={t.passed?'default':'destructive'}>{t.passed?'APROBADA':'FALLIDA'}</Badge></div>)}{order?.status==='QA'&&<Button variant="outline" onClick={async()=>{await api.deliverServiceOrder(id);await load()}}>Registrar entrega</Button>}</CardContent></Card>
  <Card><CardHeader><CardTitle>Refacciones y tiempo técnico</CardTitle></CardHeader><CardContent className="space-y-4"><form className="grid gap-2 md:grid-cols-3" onSubmit={reserve}><select required className={field} value={part.productId} onChange={e=>setPart({...part,productId:e.target.value})}><option value="">Refacción</option>{products.map(p=><option key={p.id} value={p.id}>{p.sku} · {p.name}</option>)}</select><Input type="number" min="1" value={part.quantity} onChange={e=>setPart({...part,quantity:Number(e.target.value)})}/><Button>Reservar para orden</Button></form><form className="grid gap-2 md:grid-cols-3" onSubmit={addTime}><Input type="number" min="1" value={time.minutes} onChange={e=>setTime({...time,minutes:Number(e.target.value)})}/><Input placeholder="Trabajo realizado" value={time.note} onChange={e=>setTime({...time,note:e.target.value})}/><Button>Registrar tiempo</Button></form>{times.map(t=><div className="rounded border p-2 text-sm" key={t.id}>{t.minutes} min · {t.note}</div>)}</CardContent></Card>
  <Card><CardHeader><CardTitle>Evidencia y documentos</CardTitle></CardHeader><CardContent className="space-y-3"><form className="grid gap-2" onSubmit={addDocument}><Input required placeholder="Nombre del archivo" value={document.fileName} onChange={e=>setDocument({...document,fileName:e.target.value})}/><Input required placeholder="Clave de almacenamiento o URL administrada" value={document.storageKey} onChange={e=>setDocument({...document,storageKey:e.target.value})}/><div className="grid grid-cols-2 gap-2"><Input required placeholder="image/jpeg" value={document.contentType} onChange={e=>setDocument({...document,contentType:e.target.value})}/><select className={field} value={document.accessLevel} onChange={e=>setDocument({...document,accessLevel:e.target.value})}><option>INTERNAL</option><option>CUSTOMER</option></select></div><Button>Adjuntar referencia</Button></form>{evidence.map(d=><div className="rounded border p-2 text-sm" key={d.id}>{d.fileName} · {d.accessLevel}</div>)}</CardContent></Card>
  <Card><CardHeader><CardTitle>Garantía</CardTitle></CardHeader><CardContent className="space-y-3"><form className="grid gap-2 md:grid-cols-3" onSubmit={async e=>{e.preventDefault();if(!order)return;await api.openWarrantyClaim({serviceOrderId:id,customerId:order.customerId,...warranty});await load()}}><Input required type="date" value={warranty.expiresAt} onChange={e=>setWarranty({...warranty,expiresAt:e.target.value})}/><Input required placeholder="Cobertura y motivo" value={warranty.description} onChange={e=>setWarranty({...warranty,description:e.target.value})}/><Button>Abrir garantía</Button></form>{warranties.map(w=><div className="flex items-center justify-between rounded border p-2 text-sm" key={w.id}><span>{w.description} · vence {w.expiresAt}</span><div className="flex gap-2"><Badge>{w.status}</Badge>{w.status!=='CLOSED'&&<Button size="sm" variant="outline" onClick={async()=>{await api.closeWarrantyClaim(w.id);await load()}}>Cerrar</Button>}</div></div>)}</CardContent></Card>
  <Card><CardHeader><CardTitle>Timeline</CardTitle></CardHeader><CardContent className="space-y-3">{timeline.map(h=><div className="border-l-2 pl-3" key={h.id}><p className="font-medium">{h.fromStatus??'INICIO'} → {h.toStatus}</p><p className="text-xs text-muted-foreground">{h.notes} · {h.createdAt}</p></div>)}</CardContent></Card>
  {error&&<p className="text-destructive">{error}</p>}
 </div></BaseLayout>
}
