import { useEffect, useState, type FormEvent, type ReactNode } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { ArrowRight, Wrench, Users, Package, ClipboardList } from 'lucide-react'
import { BaseLayout } from '@/components/layouts/base-layout'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Badge } from '@/components/ui/badge'
import { acceptInvitation, currentUser, forgotPassword, login, listServiceOrders, logout, portalAuthorize, portalDocuments, portalOperation, portalOtp, portalVerify, resetPassword, signup, verifyEmail, type DocumentEvidence, type PortalOperation } from './api'

function AuthCard({ title, description, children }: { title: string; description: string; children: ReactNode }) {
  return <div className="min-h-svh bg-muted/40 flex items-center justify-center p-6"><Card className="w-full max-w-md"><CardHeader><Link to="/" className="text-xl font-bold text-primary">Fixi</Link><CardTitle>{title}</CardTitle><CardDescription>{description}</CardDescription></CardHeader><CardContent>{children}</CardContent></Card></div>
}

export function Landing() {
  return <div className="min-h-svh bg-background"><header className="flex items-center justify-between border-b px-6 py-4 lg:px-16"><span className="text-2xl font-bold text-primary">Fixi</span><div className="flex gap-2"><Button variant="ghost" asChild><Link to="/login">Iniciar sesión</Link></Button><Button asChild><Link to="/signup">Crear cuenta</Link></Button></div></header><main className="mx-auto max-w-6xl px-6 py-20 lg:py-28"><div className="max-w-3xl"><Badge variant="secondary" className="mb-6">Operación inteligente para talleres</Badge><h1 className="text-5xl font-bold tracking-tight lg:text-7xl">Todo tu taller, <span className="text-primary">bajo control.</span></h1><p className="mt-6 max-w-2xl text-xl text-muted-foreground">Clientes, equipos, órdenes y técnicos en un solo lugar. Fixi convierte cada reparación en una operación clara y medible.</p><div className="mt-8 flex flex-wrap gap-3"><Button size="lg" asChild><Link to="/signup">Empieza gratis <ArrowRight className="ml-2 size-4" /></Link></Button><Button size="lg" variant="outline" asChild><Link to="/login">Ya tengo una cuenta</Link></Button></div></div><div className="mt-20 grid gap-4 md:grid-cols-3">{[[Wrench,'Órdenes de servicio','Recibe, diagnostica y entrega con trazabilidad.'],[Users,'Clientes y equipos','Conserva el historial de cada reparación.'],[Package,'Inventario','Controla refacciones y costos por orden.']].map(([Icon,title,text]) => <Card key={String(title)}><CardHeader><Icon className="size-8 text-primary"/><CardTitle className="text-lg">{String(title)}</CardTitle><CardDescription>{String(text)}</CardDescription></CardHeader></Card>)}</div></main></div>
}

export function LoginPage() {
  const navigate = useNavigate(); const [username,setUsername]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false)
  async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); setError(''); try { const result=await login(username,password); const me=await currentUser(); navigate(result.mustChangePassword ? '/settings' : me?.onboardingCompleted===false ? '/onboarding' : '/dashboard') } catch (err) { setError(err instanceof Error ? err.message : 'No se pudo iniciar sesión') } finally { setBusy(false) } }
  return <AuthCard title="Bienvenido a Fixi" description="Entra a la operación de tu negocio."><form onSubmit={submit} className="space-y-4"><div><Label htmlFor="username">Correo o usuario</Label><Input id="username" autoComplete="username" placeholder="tu@correo.com" value={username} onChange={e=>setUsername(e.target.value)} required /></div><div><div className="flex justify-between"><Label htmlFor="password">Contraseña</Label><Link className="text-sm text-primary" to="/forgot-password">¿La olvidaste?</Link></div><Input id="password" type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required /></div>{error&&<p className="text-sm text-destructive">{error}</p>}<Button className="w-full" disabled={busy}>{busy?'Entrando…':'Iniciar sesión'}</Button><p className="text-center text-sm text-muted-foreground">¿Nuevo en Fixi? <Link className="text-primary" to="/signup">Crear cuenta</Link></p></form></AuthCard>
}

export function SignupPage() { const [f,setF]=useState({ownerName:'',email:'',password:'',businessName:'',branchName:'Sucursal principal'});const [message,setMessage]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);async function submit(e:FormEvent){e.preventDefault();setError('');setMessage('');setBusy(true);try{await signup(f);setMessage('Cuenta creada. Ya puedes iniciar sesión con tu correo y contraseña.')}catch(x){setError(x instanceof Error?x.message:'No se pudo crear la cuenta')}finally{setBusy(false)}}return <AuthCard title="Crea tu cuenta Fixi" description="Crea tu negocio, propietario y primera sucursal en una sola operación."><form className="space-y-3" onSubmit={submit}><div><Label htmlFor="ownerName">Nombre del propietario</Label><Input id="ownerName" required value={f.ownerName} onChange={e=>setF({...f,ownerName:e.target.value})}/></div><div><Label htmlFor="email">Correo</Label><Input id="email" type="email" autoComplete="email" required value={f.email} onChange={e=>setF({...f,email:e.target.value})}/><p className="mt-1 text-xs text-muted-foreground">Este correo también será tu usuario para iniciar sesión.</p></div><div><Label htmlFor="password">Contraseña</Label><Input id="password" type="password" autoComplete="new-password" required value={f.password} onChange={e=>setF({...f,password:e.target.value})}/><p className="mt-1 text-xs text-muted-foreground">Mínimo 6 caracteres y al menos una mayúscula.</p></div><div><Label htmlFor="businessName">Nombre del negocio</Label><Input id="businessName" required value={f.businessName} onChange={e=>setF({...f,businessName:e.target.value})}/><p className="mt-1 text-xs text-muted-foreground">El identificador técnico se genera automáticamente.</p></div><div><Label htmlFor="branchName">Primera sucursal</Label><Input id="branchName" required value={f.branchName} onChange={e=>setF({...f,branchName:e.target.value})}/></div>{error&&<p role="alert" className="rounded-md bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}{message&&<p role="status" className="rounded-md bg-emerald-50 p-3 text-sm text-emerald-700">{message}</p>}<Button className="w-full" disabled={busy}>{busy?'Creando cuenta…':'Crear cuenta'}</Button><p className="text-center text-sm"><Link to="/login">Ya tengo cuenta</Link></p></form></AuthCard> }
export function ForgotPasswordPage(){const [email,setEmail]=useState('');const [sent,setSent]=useState(false);async function submit(e:FormEvent){e.preventDefault();await forgotPassword(email);setSent(true)}return <AuthCard title="Recupera tu acceso" description="Te enviaremos un enlace de un solo uso."><form className="space-y-4" onSubmit={submit}><Input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="tu@negocio.com"/>{sent&&<p className="text-sm text-emerald-600">Si la cuenta existe, recibirás instrucciones.</p>}<Button className="w-full">Enviar instrucciones</Button></form></AuthCard>}
export function ResetPasswordPage(){const token=new URLSearchParams(location.search).get('token')??'';const [password,setPassword]=useState('');const [done,setDone]=useState(false);async function submit(e:FormEvent){e.preventDefault();await resetPassword(token,password);setDone(true)}return <AuthCard title="Nueva contraseña" description="El enlace sólo puede utilizarse una vez.">{done?<Button asChild className="w-full"><Link to="/login">Iniciar sesión</Link></Button>:<form onSubmit={submit} className="space-y-4"><Input type="password" required value={password} onChange={e=>setPassword(e.target.value)} placeholder="12+ caracteres, mayúscula y número"/><Button className="w-full">Guardar contraseña</Button></form>}</AuthCard>}
export function VerifyEmailPage(){const token=new URLSearchParams(location.search).get('token')??'';const [state,setState]=useState('Verificando…');useEffect(()=>{verifyEmail(token).then(()=>setState('Correo verificado. Ya puedes iniciar sesión.')).catch(()=>setState('El enlace no es válido o expiró.'))},[token]);return <AuthCard title="Verificación de correo" description={state}><Button asChild className="w-full"><Link to="/login">Continuar</Link></Button></AuthCard>}
export function AcceptInvitationPage(){const token=new URLSearchParams(location.search).get('token')??'';const [f,setF]=useState({fullName:'',username:'',password:''});const [done,setDone]=useState(false);async function submit(e:FormEvent){e.preventDefault();await acceptInvitation({...f,token});setDone(true)}return <AuthCard title="Únete al equipo Fixi" description="Activa tu acceso al negocio y sucursal asignados.">{done?<Button asChild className="w-full"><Link to="/login">Iniciar sesión</Link></Button>:<form className="space-y-3" onSubmit={submit}><Input required placeholder="Nombre completo" value={f.fullName} onChange={e=>setF({...f,fullName:e.target.value})}/><Input required placeholder="Usuario" value={f.username} onChange={e=>setF({...f,username:e.target.value})}/><Input required type="password" placeholder="Contraseña segura" value={f.password} onChange={e=>setF({...f,password:e.target.value})}/><Button className="w-full">Aceptar invitación</Button></form>}</AuthCard>}

export function CustomerPortalPage(){const {token=''}=useParams();const [operation,setOperation]=useState<PortalOperation>();const [documents,setDocuments]=useState<DocumentEvidence[]>([]);const [code,setCode]=useState('');const [evidence,setEvidence]=useState('Autorizado por el cliente desde Fixi');const [verified,setVerified]=useState(false);const [message,setMessage]=useState('Validando enlace…');useEffect(()=>{Promise.all([portalOperation(token),portalDocuments(token)]).then(([o,d])=>{setOperation(o);setDocuments(d);setMessage('Solicita y valida tu código para autorizar la cotización.')}).catch(()=>setMessage('Este enlace no es válido o expiró.'))},[token]);return <AuthCard title="Portal del cliente" description={message}>{operation&&<div className="space-y-4"><p className="text-sm">Orden: <strong>{operation.resourceId}</strong></p>{documents.map(d=><div className="rounded border p-2 text-sm" key={d.id}>{d.fileName}</div>)}<Button type="button" variant="outline" className="w-full" onClick={async()=>{const r=await portalOtp(token);setMessage(r.testCode?`Código local: ${r.testCode}`:'Código enviado.')}}>Solicitar código</Button><form className="flex gap-2" onSubmit={async e=>{e.preventDefault();const r=await portalVerify(token,code);setVerified(r.verified);setMessage(r.verified?'Identidad verificada.':'Código incorrecto.')}}><Input required value={code} onChange={e=>setCode(e.target.value)} placeholder="Código OTP"/><Button>Verificar</Button></form>{verified&&<div className="space-y-2"><textarea className="w-full rounded border p-2" value={evidence} onChange={e=>setEvidence(e.target.value)}/><Button className="w-full" onClick={async()=>{await portalAuthorize(token,evidence);setMessage('Autorización registrada correctamente.')}}>Autorizar cotización</Button></div>}</div>}</AuthCard>}

function Pending({ title, description }: { title: string; description: string }) { return <BaseLayout title={title} description={description}><div className="px-4 lg:px-6"><Card><CardContent className="flex min-h-48 flex-col items-center justify-center gap-3 text-center"><ClipboardList className="size-10 text-primary"/><p className="font-medium">Módulo preparado visualmente</p><p className="max-w-md text-sm text-muted-foreground">{description}</p><Badge variant="outline">Pendiente de API</Badge></CardContent></Card></div></BaseLayout> }

export function DashboardPage() { const navigate = useNavigate(); const [busy,setBusy]=useState(false); async function signOut(){setBusy(true);try{await logout();navigate('/login')}finally{setBusy(false)}} return <BaseLayout title="Dashboard" description="La operación de tu taller, en una sola vista."><div className="flex justify-end px-4 lg:px-6"><Button variant="outline" onClick={signOut} disabled={busy}>{busy?'Saliendo…':'Cerrar sesión'}</Button></div><div className="grid gap-4 px-4 lg:grid-cols-4 lg:px-6">{[['Órdenes activas','0','text-primary'],['Esperando diagnóstico','0','text-amber-600'],['Listas para entrega','0','text-emerald-600'],['Clientes activos','0','text-blue-600']].map(([a,b,c])=><Card key={a}><CardHeader className="pb-2"><CardDescription>{a}</CardDescription><CardTitle className={`text-3xl ${c}`}>{b}</CardTitle></CardHeader></Card>)}</div><div className="px-4 pt-6 lg:px-6"><Card><CardHeader><CardTitle>Empieza con tu primera orden</CardTitle><CardDescription>Consulta la operación real del backend desde el módulo de órdenes.</CardDescription></CardHeader><CardContent><Button asChild><Link to="/service-orders">Ver órdenes de servicio</Link></Button></CardContent></Card></div></BaseLayout> }

export function ServiceOrdersPage() { const [orders,setOrders]=useState<Array<{id:string;summary:string;status:string;customerId?:string}>>([]); const [error,setError]=useState(''); useEffect(()=>{listServiceOrders().then(setOrders).catch(e=>setError(e instanceof Error?e.message:'No disponible'))},[]); return <BaseLayout title="Órdenes de servicio" description="Recepción, diagnóstico, reparación y entrega."><div className="px-4 lg:px-6"><Card><CardHeader><CardTitle>Órdenes</CardTitle><CardDescription>Datos conectados al backend Fixi/Camra existente.</CardDescription></CardHeader><CardContent>{error?<p className="text-sm text-muted-foreground">{error}</p>:orders.length===0?<p className="text-sm text-muted-foreground">No hay órdenes para mostrar.</p>:<div className="space-y-2">{orders.map(o=><div key={o.id} className="flex items-center justify-between rounded-lg border p-3"><div><p className="font-medium">{o.summary}</p><p className="text-xs text-muted-foreground">Cliente: {o.customerId??'—'}</p></div><Badge>{o.status}</Badge></div>)}</div>}</CardContent></Card></div></BaseLayout> }
export function PendingPage({ title }: { title: string }) { return <Pending title={title} description="La navegación Fixi está lista; esta capacidad se conectará al backend cuando exista su contrato."/> }
