import { useEffect,useState,type FormEvent } from 'react'
import { BaseLayout } from '@/components/layouts/base-layout'
import { Button } from '@/components/ui/button'
import { Card,CardContent,CardHeader,CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Badge } from '@/components/ui/badge'
import * as api from './api'
const field='w-full rounded-md border bg-background px-3 py-2 text-sm'
type Purchase={id:string;branchId:string;supplierId:string;serviceOrderId?:string;status:string;createdAt:string}
export function Purchases(){const [purchases,setPurchases]=useState<Purchase[]>([]);const [branches,setBranches]=useState<api.Branch[]>([]);const [suppliers,setSuppliers]=useState<api.Supplier[]>([]);const [products,setProducts]=useState<api.Product[]>([]);const [f,setF]=useState({branchId:'',supplierId:'',serviceOrderId:''});const [receipt,setReceipt]=useState({purchaseId:'',productId:'',quantity:1});async function load(){const [p,b,s,pr]=await Promise.all([api.listPurchases(),api.listBranches(),api.listSuppliers(),api.listProducts()]);setPurchases(p as Purchase[]);setBranches(b);setSuppliers(s);setProducts(pr)}useEffect(()=>{load()},[]);async function create(e:FormEvent){e.preventDefault();await api.createPurchase({...f,serviceOrderId:f.serviceOrderId||null});await load()}async function receive(e:FormEvent){e.preventDefault();await api.receivePurchase(receipt.purchaseId,{lines:[{productId:receipt.productId,quantity:receipt.quantity}]});await load()}return <BaseLayout title="Compras" description="Compra y recepción con impacto automático en inventario."><div className="grid gap-5 px-4 lg:grid-cols-2 lg:px-6"><Card><CardHeader><CardTitle>Nueva compra</CardTitle></CardHeader><CardContent><form className="space-y-3" onSubmit={create}><select required className={field} value={f.branchId} onChange={e=>setF({...f,branchId:e.target.value})}><option value="">Sucursal</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><select required className={field} value={f.supplierId} onChange={e=>setF({...f,supplierId:e.target.value})}><option value="">Proveedor</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><Input placeholder="Orden de servicio opcional" value={f.serviceOrderId} onChange={e=>setF({...f,serviceOrderId:e.target.value})}/><Button>Crear orden de compra</Button></form></CardContent></Card><Card><CardHeader><CardTitle>Recibir refacciones</CardTitle></CardHeader><CardContent><form className="space-y-3" onSubmit={receive}><select required className={field} value={receipt.purchaseId} onChange={e=>setReceipt({...receipt,purchaseId:e.target.value})}><option value="">Compra pendiente</option>{purchases.filter(p=>p.status!=='RECEIVED').map(p=><option key={p.id} value={p.id}>{p.id}</option>)}</select><select required className={field} value={receipt.productId} onChange={e=>setReceipt({...receipt,productId:e.target.value})}><option value="">Producto</option>{products.map(p=><option key={p.id} value={p.id}>{p.sku} · {p.name}</option>)}</select><Input type="number" min="1" value={receipt.quantity} onChange={e=>setReceipt({...receipt,quantity:Number(e.target.value)})}/><Button>Registrar recepción</Button></form></CardContent></Card><Card className="lg:col-span-2"><CardContent className="space-y-2 pt-6">{purchases.map(p=><div className="flex justify-between rounded border p-3" key={p.id}><span>{p.id}</span><Badge>{p.status}</Badge></div>)}</CardContent></Card></div></BaseLayout>}
