package com.hotelpms.frontdesk.assistant.engine;

/** Slot-filling and confirmation states for local assistant flows. */
public enum ConversationStep {
    NONE,
    WAITING_GUEST_NAME,
    WAITING_GUEST_SELECTION,
    WAITING_CREATE_GUEST_DECISION,
    WAITING_FIRST_NAME,
    WAITING_LAST_NAME,
    WAITING_EMAIL,
    WAITING_CREATE_GUEST_CONFIRMATION,
    WAITING_CHECKIN_DATE,
    WAITING_CHECKOUT_DATE,
    WAITING_SINGLE_DATE_MEANING,
    WAITING_ROOM_TYPE,
    WAITING_ROOM_SELECTION,
    WAITING_ROOM_ALTERNATIVE,
    WAITING_OCCUPANT_COUNT,
    WAITING_CHECKIN_CONFIRMATION,

    WAITING_BATCH_COUNT,
    WAITING_BATCH_ORIGIN_TYPE,
    WAITING_BATCH_ORGANIZATION_NAME,
    WAITING_BATCH_BILLING_MODE,
    WAITING_BATCH_GUEST_LIST,
    WAITING_BATCH_CONFIRMATION
}
