package com.hotelpms.guest.service.impl;
import com.hotelpms.guest.dto.request.DeviceRequest; import com.hotelpms.guest.dto.response.DeviceResponse; import com.hotelpms.guest.exception.NotFoundException; import com.hotelpms.guest.model.Device; import com.hotelpms.guest.repository.DeviceRepository; import com.hotelpms.guest.repository.GuestRepository; import com.hotelpms.guest.service.DeviceService; import lombok.RequiredArgsConstructor; import org.springframework.security.core.context.SecurityContextHolder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.LocalDateTime; import java.util.*;
@Service @RequiredArgsConstructor public class DeviceServiceImpl implements DeviceService {
 private final DeviceRepository devices; private final GuestRepository guests;
 private UUID hotel(){ Object details = SecurityContextHolder.getContext().getAuthentication().getDetails(); return details instanceof UUID ? (UUID) details : UUID.fromString(String.valueOf(details)); }
 private void customer(UUID id){ if(!guests.findByIdAndHotelId(id,hotel()).isPresent()) throw new NotFoundException("CUSTOMER_NOT_FOUND"); }
 @Transactional public DeviceResponse create(UUID customerId, DeviceRequest r){ UUID h=hotel(); customer(customerId); if(r.serialNumber()!=null && devices.findByHotelIdAndGuestIdAndSerialNumber(h,customerId,r.serialNumber()).isPresent()) throw new IllegalArgumentException("DEVICE_IDENTITY_ALREADY_EXISTS"); if(r.imei()!=null && devices.findByHotelIdAndGuestIdAndImei(h,customerId,r.imei()).isPresent()) throw new IllegalArgumentException("DEVICE_IDENTITY_ALREADY_EXISTS"); Device d=Device.builder().hotelId(h).guestId(customerId).category(r.category()).manufacturer(r.manufacturer()).model(r.model()).serialNumber(r.serialNumber()).imei(r.imei()).customFields(r.customFields()).createdAt(LocalDateTime.now()).updatedAt(LocalDateTime.now()).build(); return DeviceResponse.from(devices.save(d)); }
 @Transactional(readOnly=true) public List<DeviceResponse> list(UUID c){ customer(c); return devices.findAllByHotelIdAndGuestId(hotel(),c).stream().map(DeviceResponse::from).toList(); }
 @Transactional(readOnly=true) public DeviceResponse get(UUID c,UUID id){ customer(c); return devices.findByIdAndHotelIdAndGuestId(id,hotel(),c).map(DeviceResponse::from).orElseThrow(()->new NotFoundException("DEVICE_NOT_FOUND")); }
}
