package com.hotelpms.frontdesk.workflow.controller;
import com.hotelpms.frontdesk.workflow.domain.*; import com.hotelpms.frontdesk.workflow.dto.WorkflowDtos.*; import com.hotelpms.frontdesk.workflow.service.WorkflowService; import jakarta.validation.Valid; import lombok.RequiredArgsConstructor; import org.springframework.http.*; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.security.core.context.SecurityContextHolder; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/api/v1/workflows") @RequiredArgsConstructor public class WorkflowController { private final WorkflowService service;
 @PostMapping @PreAuthorize("hasAuthority('workflows.manage')") public ResponseEntity<WorkflowResponse> create(@Valid @RequestBody CreateWorkflowRequest r){WorkflowDefinition w=service.create(hotel(),r);return ResponseEntity.status(HttpStatus.CREATED).body(view(w));}
 @PostMapping("/{id}/states") @PreAuthorize("hasAuthority('workflows.manage')") public StateResponse state(@PathVariable UUID id,@Valid @RequestBody AddStateRequest r){return stateView(service.addState(hotel(),id,r));}
 @PostMapping("/{id}/transitions") @PreAuthorize("hasAuthority('workflows.manage')") public TransitionResponse transitionDef(@PathVariable UUID id,@Valid @RequestBody AddTransitionRequest r){return transitionView(service.addTransition(hotel(),id,r));}
 @PostMapping("/{id}/transition") @PreAuthorize("hasAuthority('workflow.transition')") public TransitionResponse transition(@PathVariable UUID id,@Valid @RequestBody TransitionRequest r){var authentication=SecurityContextHolder.getContext().getAuthentication(); var candidate=service.transitions(hotel(),id).stream().filter(t -> t.getKey().equals(r.transitionKey()) && t.getFromState().getKey().equals(r.fromStateKey())).findFirst().orElseThrow(() -> new com.hotelpms.frontdesk.exception.ConflictException("Transition is not allowed from current state")); if(authentication.getAuthorities().stream().noneMatch(a -> a.getAuthority().equals(candidate.getRequiredPermission()))) throw new org.springframework.security.access.AccessDeniedException("Missing workflow permission"); return transitionView(service.transition(hotel(),id,r,String.valueOf(authentication.getPrincipal())));}
 @GetMapping("/{id}") @PreAuthorize("hasAuthority('workflows.read')") public WorkflowResponse get(@PathVariable UUID id){return view(service.definition(hotel(),id));}
 private WorkflowResponse view(WorkflowDefinition w){return new WorkflowResponse(w.getId(),w.getVerticalKey(),w.getName(),w.getVersion(),service.states(hotel(),w.getId()).stream().map(this::stateView).toList(),service.transitions(hotel(),w.getId()).stream().map(this::transitionView).toList());} private StateResponse stateView(WorkflowState s){return new StateResponse(s.getKey(),s.getLabel(),s.getSemanticPhase(),s.isInitialState(),s.isTerminalState());} private TransitionResponse transitionView(WorkflowTransition t){return new TransitionResponse(t.getKey(),t.getFromState().getKey(),t.getToState().getKey(),t.getRequiredPermission());} private UUID hotel(){return UUID.fromString(String.valueOf(SecurityContextHolder.getContext().getAuthentication().getDetails()));} }
